/**
 * @file    main.c
 * @brief   LoRa Camera Trigger — Placeholder Firmware
 *          STM32WLE5C8U6
 *
 * PLACEHOLDER — intended for initial hardware bring-up only.
 * Replace LoRa driver calls, trigger verification, and RunCam
 * control with production implementations before flight.
 *
 * Hardware:
 *   PA0  — BOOST_EN (output, active high releases EN pull-up → camera on)
 *   PA2  — USART2_TX → RunCam RX
 *   PA3  — USART2_RX ← RunCam TX
 *   PA6  — VCTL1 RF switch (HIGH = TX path)
 *   PA7  — VCTL2 RF switch (HIGH = RX path, complementary to VCTL1)
 *   PA9  — USART1_TX → CH340C (debug UART)
 *   PA10 — USART1_RX ← CH340C
 *   PA13 — SWDIO
 *   PA14 — SWDCLK
 *   PH3  — BOOT0
 *
 * Boot sequence:
 *   1. PA0 driven LOW immediately — boost off, camera off
 *   2. RF switch set to RX mode (VCTL1=0, VCTL2=1)
 *   3. SubGHz radio initialised, listening on configured frequency
 *   4. On valid trigger packet received → release PA0 → camera latches on
 *   5. Send RunCam record start command over USART2
 *   6. PA0 never driven low again — camera stays on for remainder of flight
 */

#include "main.h"
#include "subghz.h"
#include <string.h>
#include <stdio.h>

/* ─── User configuration ──────────────────────────────────────────────────── */

/* LoRa radio settings — adjust to match your ground transmitter */
#define LORA_FREQUENCY_HZ       915000000UL   /* 915 MHz — change to 868000000 for EU */
#define LORA_SPREADING_FACTOR   7             /* SF7 = faster, shorter range. SF12 = slower, max range */
#define LORA_BANDWIDTH          SUBGHZ_LORA_BW_125KHZ
#define LORA_CODING_RATE        SUBGHZ_LORA_CR_4_5
#define LORA_PREAMBLE_LENGTH    8
#define LORA_SYNCWORD           0x12          /* Private LoRa network sync word */
#define LORA_TX_POWER_DBM       14            /* dBm — low power mode max ~15dBm */

/*
 * Trigger packet magic bytes.
 * PLACEHOLDER — replace with a proper authentication scheme before flight.
 * Any received packet containing this sequence triggers the camera.
 * Keep this secret and unique to your rocket to avoid false triggers.
 */
#define TRIGGER_MAGIC_0         0xCA
#define TRIGGER_MAGIC_1         0xFE
#define TRIGGER_MAGIC_2         0xBA
#define TRIGGER_MAGIC_3         0xBE
#define TRIGGER_MAGIC_LEN       4

/* RunCam protocol — record start command */
/* https://support.runcam.com/hc/en-us/articles/360014537794 */
#define RUNCAM_HEADER           0xCC
#define RUNCAM_RECORD_START     0x01
#define RUNCAM_RECORD_STOP      0x02

/* ─── GPIO helpers ────────────────────────────────────────────────────────── */

/* BOOST_EN — PA0 */
#define BOOST_EN_PORT           GPIOA
#define BOOST_EN_PIN            GPIO_PIN_0

/* RF switch control — PA6 (VCTL1), PA7 (VCTL2) */
#define RF_VCTL1_PORT           GPIOA
#define RF_VCTL1_PIN            GPIO_PIN_6
#define RF_VCTL2_PORT           GPIOA
#define RF_VCTL2_PIN            GPIO_PIN_7

/* ─── State ───────────────────────────────────────────────────────────────── */

typedef enum {
    STATE_BOOT = 0,
    STATE_RX_IDLE,          /* Waiting for LoRa trigger */
    STATE_TRIGGERED,        /* Camera on, recording */
    STATE_ERROR             /* Something went wrong */
} SystemState_t;

static SystemState_t system_state = STATE_BOOT;
static volatile uint8_t rx_buffer[255];
static volatile uint8_t rx_length = 0;
static volatile uint8_t packet_received = 0;

/* HAL handles — generated by CubeMX, declared extern here */
extern SUBGHZ_HandleTypeDef hsubghz;
extern UART_HandleTypeDef   huart1;     /* Debug / CH340C */
extern UART_HandleTypeDef   huart2;     /* RunCam */

/* ─── Function prototypes ─────────────────────────────────────────────────── */

static void     gpio_init_safe(void);
static void     rf_switch_set_rx(void);
static void     rf_switch_set_tx(void);
static HAL_StatusTypeDef lora_init(void);
static HAL_StatusTypeDef lora_start_rx(void);
static uint8_t  verify_trigger_packet(const uint8_t *buf, uint8_t len);
static void     trigger_camera(void);
static void     runcam_send_record_start(void);
static void     debug_print(const char *msg);
static void     error_handler(const char *msg);

/* ─── Main ────────────────────────────────────────────────────────────────── */

int main(void)
{
    /* HAL and clock init — generated by CubeMX */
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_SUBGHZ_Init();

    /*
     * SAFETY CRITICAL — must happen before anything else.
     * Drive BOOST_EN low immediately so camera stays off
     * regardless of the R_EN_PU pull-up on the EN rail.
     */
    gpio_init_safe();

    debug_print("\r\n--- LoRa Camera Trigger ---\r\n");
    debug_print("Boot OK. Camera OFF. Initialising radio...\r\n");

    /* Initialise the SubGHz radio */
    if (lora_init() != HAL_OK) {
        error_handler("Radio init failed");
    }

    /* Set RF switch to RX mode before starting receive */
    rf_switch_set_rx();

    /* Start continuous receive */
    if (lora_start_rx() != HAL_OK) {
        error_handler("RX start failed");
    }

    system_state = STATE_RX_IDLE;
    debug_print("Listening for trigger packet...\r\n");

    /* ── Main loop ── */
    while (1)
    {
        if (packet_received)
        {
            packet_received = 0;

            debug_print("Packet received. Verifying...\r\n");

            if (verify_trigger_packet((const uint8_t *)rx_buffer, rx_length))
            {
                debug_print("Valid trigger! Activating camera.\r\n");
                trigger_camera();
                system_state = STATE_TRIGGERED;

                /*
                 * Camera is now on and latched via hardware pull-up.
                 * PA0 is set high-Z — EN held HIGH by R_EN_PU.
                 * Do not drive PA0 low again.
                 *
                 * PLACEHOLDER: In production firmware, you may want to:
                 *   - Send a LoRa acknowledgement back to ground
                 *   - Log flight events
                 *   - Monitor battery voltage via ADC
                 *   - Enter low power mode to conserve battery
                 */
                debug_print("Camera latched ON. Entering idle.\r\n");

                /* Optional: send ack */
                /* rf_switch_set_tx(); */
                /* lora_send_ack(); */
                /* rf_switch_set_rx(); */

                /* Stay alive but do nothing — camera runs until battery dies */
                while (1) {
                    HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
                }
            }
            else
            {
                debug_print("Packet invalid — ignoring. Still listening.\r\n");

                /* Restart RX after receiving a packet */
                rf_switch_set_rx();
                lora_start_rx();
            }
        }

        /* Low power sleep between packets */
        HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
    }
}

/* ─── GPIO safe init ──────────────────────────────────────────────────────── */

/**
 * @brief Configure safety-critical GPIO pins immediately after boot.
 *        MUST be called before any other initialisation.
 */
static void gpio_init_safe(void)
{
    GPIO_InitTypeDef gpio = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* BOOST_EN (PA0) — output LOW immediately, camera off */
    HAL_GPIO_WritePin(BOOST_EN_PORT, BOOST_EN_PIN, GPIO_PIN_RESET);
    gpio.Pin   = BOOST_EN_PIN;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BOOST_EN_PORT, &gpio);

    /* RF switch VCTL1 (PA6) — LOW initially (RX mode) */
    HAL_GPIO_WritePin(RF_VCTL1_PORT, RF_VCTL1_PIN, GPIO_PIN_RESET);
    gpio.Pin = RF_VCTL1_PIN;
    HAL_GPIO_Init(RF_VCTL1_PORT, &gpio);

    /* RF switch VCTL2 (PA7) — HIGH initially (RX mode) */
    HAL_GPIO_WritePin(RF_VCTL2_PORT, RF_VCTL2_PIN, GPIO_PIN_SET);
    gpio.Pin = RF_VCTL2_PIN;
    HAL_GPIO_Init(RF_VCTL2_PORT, &gpio);
}

/* ─── RF switch ───────────────────────────────────────────────────────────── */

/**
 * @brief Set RF switch to receive mode.
 *        VCTL1=0, VCTL2=1 → INPUT connected to OUTPUT2 (RFI_in → balun)
 */
static void rf_switch_set_rx(void)
{
    HAL_GPIO_WritePin(RF_VCTL1_PORT, RF_VCTL1_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(RF_VCTL2_PORT, RF_VCTL2_PIN, GPIO_PIN_SET);
}

/**
 * @brief Set RF switch to transmit mode.
 *        VCTL1=1, VCTL2=0 → INPUT connected to OUTPUT1 (RFO_out → balun)
 */
static void rf_switch_set_tx(void)
{
    HAL_GPIO_WritePin(RF_VCTL1_PORT, RF_VCTL1_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(RF_VCTL2_PORT, RF_VCTL2_PIN, GPIO_PIN_RESET);
}

/* ─── LoRa radio ──────────────────────────────────────────────────────────── */

/**
 * @brief Initialise the STM32WLE5 SubGHz radio in LoRa mode.
 *
 * PLACEHOLDER — this uses ST's SubGHz HAL directly.
 * In production, consider using ST's LoRaWAN middleware or
 * the SubGHz_Phy component from STM32CubeWL for a cleaner abstraction.
 */
static HAL_StatusTypeDef lora_init(void)
{
    HAL_StatusTypeDef status;

    /* Wake the radio from sleep */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_STANDBY,
                                    (uint8_t[]){STDBY_RC}, 1);
    if (status != HAL_OK) return status;

    /* Set packet type to LoRa */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_PACKETTYPE,
                                    (uint8_t[]){PACKET_TYPE_LORA}, 1);
    if (status != HAL_OK) return status;

    /* Set frequency */
    uint32_t freq = LORA_FREQUENCY_HZ;
    uint8_t freq_buf[4] = {
        (freq >> 24) & 0xFF,
        (freq >> 16) & 0xFF,
        (freq >>  8) & 0xFF,
        (freq      ) & 0xFF
    };
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_RFFREQUENCY, freq_buf, 4);
    if (status != HAL_OK) return status;

    /* Set TX power and ramp time — low power PA */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_TXPARAMS,
                                    (uint8_t[]){LORA_TX_POWER_DBM, RADIO_RAMP_200_US}, 2);
    if (status != HAL_OK) return status;

    /*
     * Set PA config for low power mode (RFO_LP).
     * paDutyCycle=0x04, hpMax=0x00, deviceSel=0x01 (LP PA), paLUT=0x01
     */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_PACONFIG,
                                    (uint8_t[]){0x04, 0x00, 0x01, 0x01}, 4);
    if (status != HAL_OK) return status;

    /* Set LoRa modulation params: SF, BW, CR, LDRO */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_MODULATIONPARAMS,
                                    (uint8_t[]){
                                        LORA_SPREADING_FACTOR,
                                        LORA_BANDWIDTH,
                                        LORA_CODING_RATE,
                                        0x00   /* LDRO off — enable for SF11/SF12 */
                                    }, 4);
    if (status != HAL_OK) return status;

    /* Set LoRa packet params: preamble, header type, payload len, CRC, IQ */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_PACKETPARAMS,
                                    (uint8_t[]){
                                        0x00, LORA_PREAMBLE_LENGTH,  /* preamble MSB/LSB */
                                        0x00,                         /* explicit header */
                                        0xFF,                         /* max payload length */
                                        0x01,                         /* CRC on */
                                        0x00                          /* standard IQ */
                                    }, 6);
    if (status != HAL_OK) return status;

    /* Set sync word — 0x1424 for private network (maps from 0x12) */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_LORA_SYMB_NUM_TIMEOUT,
                                    (uint8_t[]){0x00}, 1);
    if (status != HAL_OK) return status;

    /* Enable RX done and timeout interrupts on DIO1 */
    status = HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_CFG_DIOIRQ,
                                    (uint8_t[]){
                                        0x02, 0x02,  /* IRQ mask: RX done */
                                        0x02, 0x02,  /* DIO1 map: RX done */
                                        0x00, 0x00,  /* DIO2 */
                                        0x00, 0x00   /* DIO3 */
                                    }, 8);
    if (status != HAL_OK) return status;

    return HAL_OK;
}

/**
 * @brief Start continuous LoRa receive.
 */
static HAL_StatusTypeDef lora_start_rx(void)
{
    /* Continuous RX: timeout = 0xFFFFFF */
    return HAL_SUBGHZ_ExecSetCmd(&hsubghz, RADIO_SET_RX,
                                  (uint8_t[]){0xFF, 0xFF, 0xFF}, 3);
}

/* ─── Trigger verification ────────────────────────────────────────────────── */

/**
 * @brief Check received packet for valid trigger magic bytes.
 *
 * PLACEHOLDER — checks first 4 bytes against magic sequence.
 * Replace with HMAC, rolling code, or other auth before flight.
 *
 * @param buf  Received packet buffer
 * @param len  Packet length
 * @return 1 if valid trigger, 0 otherwise
 */
static uint8_t verify_trigger_packet(const uint8_t *buf, uint8_t len)
{
    if (len < TRIGGER_MAGIC_LEN) return 0;

    return (buf[0] == TRIGGER_MAGIC_0 &&
            buf[1] == TRIGGER_MAGIC_1 &&
            buf[2] == TRIGGER_MAGIC_2 &&
            buf[3] == TRIGGER_MAGIC_3) ? 1 : 0;
}

/* ─── Camera trigger ──────────────────────────────────────────────────────── */

/**
 * @brief Release BOOST_EN and send RunCam record start command.
 *        Once called, do not drive PA0 low again.
 */
static void trigger_camera(void)
{
    /*
     * Release PA0 — set to input (high-Z).
     * R_EN_PU (100k) pulls EN HIGH → TPS61023 enables → 5V to camera.
     * This is a one-way operation for this flight.
     */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin  = BOOST_EN_PIN;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(BOOST_EN_PORT, &gpio);

    /* Small delay to let boost rail come up (TPS61023 soft-start ~2ms) */
    HAL_Delay(10);

    /* Send RunCam record start */
    runcam_send_record_start();
}

/* ─── RunCam protocol ─────────────────────────────────────────────────────── */

/**
 * @brief Send RunCam protocol record start command over USART2.
 *
 * RunCam protocol: [0xCC] [command] [CRC]
 * CRC = XOR of all previous bytes.
 *
 * PLACEHOLDER — basic implementation, verify against RunCam
 * Split 4 V2 documentation before flight.
 */
static void runcam_send_record_start(void)
{
    uint8_t cmd[3];
    cmd[0] = RUNCAM_HEADER;
    cmd[1] = RUNCAM_RECORD_START;
    cmd[2] = cmd[0] ^ cmd[1];  /* Simple XOR CRC */

    HAL_UART_Transmit(&huart2, cmd, 3, 100);
}

/* ─── Debug UART ──────────────────────────────────────────────────────────── */

static void debug_print(const char *msg)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)msg, strlen(msg), 100);
}

/* ─── Error handler ───────────────────────────────────────────────────────── */

static void error_handler(const char *msg)
{
    system_state = STATE_ERROR;
    debug_print("ERROR: ");
    debug_print(msg);
    debug_print("\r\n");

    /*
     * In error state: keep camera off, blink LED if available,
     * and loop indefinitely. Do not trigger camera on error.
     */
    while (1) {
        HAL_Delay(500);
    }
}

/* ─── SubGHz IRQ callback ─────────────────────────────────────────────────── */

/**
 * @brief Called by HAL when SubGHz radio interrupt fires.
 *        Reads received packet into rx_buffer and sets flag for main loop.
 */
void HAL_SUBGHZ_RxCpltCallback(SUBGHZ_HandleTypeDef *hsubghz)
{
    uint8_t irq_status[2];
    uint8_t rx_buf_status[2];

    /* Read IRQ status */
    HAL_SUBGHZ_ExecGetCmd(hsubghz, RADIO_GET_IRQSTATUS, irq_status, 2);

    /* Clear IRQ */
    HAL_SUBGHZ_ExecSetCmd(hsubghz, RADIO_CLR_IRQSTATUS, irq_status, 2);

    /* Check RX done bit */
    if (irq_status[1] & 0x02)
    {
        /* Get buffer status (payload length + start offset) */
        HAL_SUBGHZ_ExecGetCmd(hsubghz, RADIO_GET_RXBUFFERSTATUS, rx_buf_status, 2);

        rx_length = rx_buf_status[0];
        if (rx_length > sizeof(rx_buffer)) rx_length = sizeof(rx_buffer);

        /* Read payload from radio buffer */
        HAL_SUBGHZ_ReadBuffer(hsubghz, rx_buf_status[1],
                              (uint8_t *)rx_buffer, rx_length);

        packet_received = 1;
    }
}
